# Generated by Django 2.2.6 on 2019-10-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('nom', models.CharField(blank=True, max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=50, verbose_name='Prenom')),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('avatar', models.ImageField(blank=True, upload_to='images/')),
                ('date_debut', models.DateField(verbose_name='Date debut reservation')),
                ('date_fin', models.DateField(verbose_name='Date fin reservation')),
                ('validee', models.BooleanField(default=False)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Chambre')),
            ],
        ),
    ]
