# Generated by Django 2.2.6 on 2019-10-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='type_chambre',
            new_name='chambre',
        ),
    ]
