# Generated by Django 2.2.6 on 2019-10-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typechambre',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel'),
        ),
    ]
