# Generated by Django 2.2.6 on 2019-10-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='nombre_chambres',
            field=models.IntegerField(verbose_name='Nombre de chambres dans ce type'),
        ),
    ]
