# Generated by Django 2.2.6 on 2019-10-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20191011_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='hotels.Hotel'),
        ),
    ]
