# Generated by Django 2.2.6 on 2019-10-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20191010_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typechambre',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
