# Generated by Django 2.2.6 on 2019-10-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(upload_to='statics/images'),
        ),
    ]
