# Generated by Django 2.2.6 on 2019-10-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191010_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='statics/images'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, verbose_name='Prenom'),
        ),
    ]
